using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.ComponentModel.DataAnnotations;
using System.IO;

namespace Smeat.Leader.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IHtmlLocalizer _localizer;
        protected readonly IHostingEnvironment _hostingEnvironment;

        public IndexModel(ILogger<IndexModel> logger, IHtmlLocalizer<IndexModel> localizer, IHostingEnvironment hostingEnvironment)
        {
            _logger = logger;
            _localizer = localizer;
            _hostingEnvironment = hostingEnvironment;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required(ErrorMessage = "{0} is required")]
            [StringLength(100)]
            [EmailAddress]
            [Display(Name = "Search")]
            public string Search { get; set; }
        }

        public void OnGet()
        {
            _logger.LogDebug("Entering Index OnGet() method");

            ViewData["Welcome"] = _localizer["Welcome"];
            ViewData["BuildInfo"] = ReadBuildInfo();
        }

        /// <summary>
        /// Read build info generated by CI
        /// </summary>
        /// <returns></returns>
        private string ReadBuildInfo()
        {
            try
            {
                var reader = new StreamReader(_hostingEnvironment.WebRootPath + "\\buildinfo.txt");
                var fileContents = reader.ReadToEnd();
                return fileContents;
            }
            catch
            {
                return "Error reading build info";
            }
        }
    }
}
